### PR TITLE
Fix Bandit Issues

### PR DESCRIPTION
**Pull request by bdwyer2**

### CODE REVIEW

**Comment by kmh4321** [comment]
@bdwyer2 do we wait for Travis?

**Comment by bdwyer2** [comment]
Travis will fail due to flake8 issues. I was planning on opening another PR to fix the flake8 stuff

**Comment by bdwyer2** [comment]
Bandit works. The test are failing for other reasons.
`The command "bandit -r ." exited with 0.`

@kmh4321 should we disable `test.py` until we can get that working?

**Comment by kmh4321** [comment]
@bdwyer2 yes we can disable tests.

**Pull request merged**
